package com.uygemre.qrcode.enums

enum class IntentBundleKeyEnum {
    DETAIL_KEY,
    DETAIL_WEB_URL,
    DETAIL_DOCUMENT,
    DETAIL_CONTACT,
    DETAIL_EMAIL,
    DETAIL_SMS,
    DETAIL_LOCATION,
    DETAIL_PHONE,
    DETAIL_CALENDAR,
    DETAIL_WIFI,
    DETAIL_TWITTER,
    DETAIL_WHATSAPP,
    DETAIL_LINKEDIN,
    DETAIL_YOUTUBE,
    DETAIL_INSTAGRAM,
    DETAIL_PREMIUM_SUBSCRIBE
}